### ISSUE TITLE
environment.conf empty string

### ISSUE THREAD

**Issue by jonmosco** [example42/control-repo#65]
with the environment.conf config_version, I always get an empty string:

Info: Applying configuration version ''

config_version = '/usr/bin/git --git-dir /etc/puppetlabs/code/environments/$environment/.git  log --pretty=format:"%h - %an, %ad : %s" -1'

This does work on the command line as expected.

**Comment by alvagante** [comment]
Going to check, in the meantime can you tell me in which context this happens? (On vagrant boxes, in a deployed puppetmaster-clients environment...)

**Comment by jonmosco** [comment]
This happens in a deployed puppet environment, one with enterprise 2015.3.1, and one FOSS 4.x

**Comment by jonmosco** [comment]
I was able to get this to work calling a bash script:

config_version = 'scripts/commit_msg.sh $environment'

**Comment by alvagante** [comment]
Thanks for the tip, can you confirm me if the referenced commit fixes the issue?
