### ISSUE TITLE
tools::user::managed Unknown variable: 'real_gid' with default parameter values

### ISSUE THREAD

**Issue by snesbittsea** [example42/control-repo#82]
Given a hiera definition as follows:
  profile::users::static::managed_users:
    test_user:
      comment: 'test_user'

and an attempt to include profile::users::static

tools::user::managed will fail to compile with an unknown variable: real_gid.

Problem is the if test on uid at line 194. If uid = 'absent' then no value for real_gid is ever set and boom.

Probably should contain an else clause that set real_gid to undef

**Comment by alvagante** [comment]
https://github.com/example42/control-repo/pull/83/commits/a3f1b3fa6ff3208c92d591c7c6938fc963f2dbd7 should have fixed. Thanks for the notice
