### ISSUE TITLE
Puppetfile is missing "puppetlabs/apt"

### ISSUE THREAD

**Issue by ZyanKLee** [example42/control-repo#86]
To install docker using `bin/setup.sh` the apt module by puppetlabs (or drop-in replacement) is required.
Puppetfile however does not state it in "production" and so the module is never installed - docker fails to install.

**Comment by alvagante** [comment]
The problem was due to a duplicated entry for docker module, example42 one does not need puppetlabs-apt , gareth's one yes, and for some reasons both of them were added in the Puppetfile.
Now only the ex42 is there and there should no need of puppetlabs-apt
